FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN corepack enable
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/api/package.json apps/api/package.json
RUN pnpm install --prod --frozen-lockfile --ignore-scripts
COPY public ./public
COPY .next ./.next
EXPOSE 3000
CMD ["pnpm", "start", "--hostname", "0.0.0.0"]
