"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ShieldCheck, Lock, ArrowLeft } from "lucide-react";
import { AuthAlert } from "@/components/auth/AuthAlert";

export default function MfaVerificationPage() {
  const router = useRouter();
  const [code, setCode] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [alert, setAlert] = useState<{ type: "error" | "success"; message: string } | null>(null);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (code.length !== 6) {
      setAlert({ type: "error", message: "Please enter a valid 6-digit TOTP code." });
      return;
    }

    setIsLoading(true);
    setAlert(null);

    try {
      const res = await fetch("/api/v1/auth/mfa/verify", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ code }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.error || "MFA verification failed.");
      }

      setAlert({ type: "success", message: "MFA code verified! Redirecting..." });
      setTimeout(() => {
        router.push("/employer/dashboard");
      }, 800);
    } catch (err: any) {
      setAlert({ type: "error", message: err.message || "Invalid MFA code." });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 flex items-center justify-center p-4 py-12 text-slate-900 dark:text-slate-100">
      <div className="w-full max-w-md bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-8 shadow-2xl space-y-6">
        <Link href="/auth/login" className="inline-flex items-center gap-1 text-xs font-semibold text-slate-500 hover:text-slate-900">
          <ArrowLeft className="h-3.5 w-3.5" /> Back to Sign In
        </Link>

        <div className="text-center space-y-2">
          <div className="w-14 h-14 rounded-full bg-blue-100 text-blue-600 dark:bg-blue-950 dark:text-blue-400 mx-auto flex items-center justify-center">
            <ShieldCheck className="h-7 w-7" />
          </div>
          <h1 className="text-2xl font-black">Two-Factor Verification</h1>
          <p className="text-xs text-slate-500 leading-relaxed">
            Enter the 6-digit security code generated by your Authenticator application
          </p>
        </div>

        {alert && <AuthAlert type={alert.type} message={alert.message} />}

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-600 dark:text-slate-400 mb-1 text-center">
              6-Digit Security Code
            </label>
            <input
              type="text"
              maxLength={6}
              required
              placeholder="000 000"
              value={code}
              onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
              className="w-full h-12 text-center font-mono text-lg font-black tracking-widest rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 focus:outline-none focus:border-blue-600"
            />
          </div>

          <button
            type="submit"
            disabled={isLoading || code.length !== 6}
            className="w-full h-11 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs shadow-md shadow-blue-500/20 disabled:opacity-50"
          >
            {isLoading ? "Verifying Code..." : "Verify & Continue"}
          </button>
        </form>
      </div>
    </div>
  );
}
